[project]
name = "deepschool-final"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "asyncpg>=0.30.0",
    "pypdf2>=3.0.1",
    "python-dotenv>=1.1.1",
    "python-telegram-bot>=22.5",
    "together>=1.5.26",
]
